# Generated by Django 4.1.4 on 2023-01-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('tour_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('tour_info', models.CharField(max_length=100)),
                ('places', models.ImageField(blank=True, upload_to='places/')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('day_one', models.TextField(blank=True)),
                ('day_two', models.TextField(blank=True)),
                ('day_three', models.TextField(blank=True)),
                ('day_four', models.TextField(blank=True)),
                ('day_five', models.TextField(blank=True)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('guests', models.IntegerField()),
                ('price', models.IntegerField()),
                ('meet_time', models.DateTimeField()),
                ('cancel_policy', models.CharField(max_length=100)),
            ],
        ),
    ]
