# Generated by Django 4.1.4 on 2023-01-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemodel',
            name='place_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='packagemodel',
            name='tour_info',
            field=models.TextField(blank=True),
        ),
    ]
