# Generated by Django 4.1.4 on 2023-01-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursApp', '0003_remove_packagemodel_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('destination', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
