# Generated by Django 4.1.4 on 2023-01-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursApp', '0008_profilemodel_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
