# Generated by Django 4.1.4 on 2023-01-10 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToursApp', '0009_alter_profilemodel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemodel',
            name='places1',
            field=models.ImageField(blank=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='places2',
            field=models.ImageField(blank=True, upload_to='places/'),
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='places3',
            field=models.ImageField(blank=True, upload_to='places/'),
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('bookid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('numdays', models.IntegerField()),
                ('payment_method', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=100)),
                ('people', models.IntegerField(blank=True)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ToursApp.packagemodel')),
            ],
        ),
    ]
