# Generated by Django 4.1.4 on 2023-01-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursApp', '0010_packagemodel_places1_packagemodel_places2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='tour_id',
            field=models.CharField(max_length=100),
        ),
    ]
