# Generated by Django 4.1.4 on 2023-01-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToursApp', '0011_alter_bookingmodel_tour_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='to_date',
        ),
    ]
