# Generated by Django 4.1.4 on 2023-01-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursApp', '0013_alter_packagemodel_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storytype', models.CharField(default='userstory', max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='stories/')),
                ('desc', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
