# Generated by Django 4.1.4 on 2023-01-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursApp', '0015_contactusmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='feedback',
            field=models.TextField(),
        ),
    ]
